---
-  hosts: apic
   any_errors_fatal: true
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
    
   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: 'sandboxapicdc.cisco.com'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: '!v3G@!4@Y'
       private: yes
       unsafe: yes


   vars_files:
     - /root/ACI_Objects_Creator/files/source.yml


   tasks:
   
   - name: print with_dict output
     ansible.builtin.debug:
       msg: "{{ item }}"
     with_subelements: 
       - "{{ tenants }}"
       - "bridge_domains"
          
   - name: print subnet maks output
     debug:
       msg: "{{ item.1.subnets.0.name }}"
     with_subelements: 
       - "{{ tenants }}"
       - "bridge_domains"
      

#   - name: Display bd list
#     tags: bd
#     debug:
#       var: item
#     loop: "{{ jsondata  | json_query('tenants[*].bridge_domains[]') | list }}"
      

#  - name: with_subelements -> loop
#     tags: bd
#     debug:
#       msg: "{{ item.1.subnets.0.mask }}"
#     loop: "{{ jsondata | subelements('bridge_domains[]') }}"


