---
-  hosts: apic
   any_errors_fatal: true
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
    
   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: 'sandboxapicdc.cisco.com'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: '!v3G@!4@Y'
       private: yes
       unsafe: yes

   tasks:
 
#   - name: Calling Variabl File
#     include_vars: coding_challenge_ansible.json

   - name: Display the JSON file content
     shell: cat coding_challenge_ansible.json
     register: result

   - name: save the Json data to a Variable as a Fact
     set_fact:
       jsondata: "{{ result.stdout | from_json }}"


   - name: Create a tenant
     aci_tenant:
       tenant: "{{ jsondata | json_query('tenants.name') | first }}"
       description: "ddcd"
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       validate_certs: false


  #  group_id: "{{ groups | json_query(query) | first }}"
  # vars:
  #  query: "json[?name=='{{ group_name }}'].id"


#   - name: Create a tenant
#     aci_tenant:
#       tenant: "{{ item.name) }}"
#       description: "{{ item.description) }}"
#       host: "{{ inventory_hostname }}"
#       username: "{{ user }}"
#       password: "{{ pass }}"
#       validate_certs: false
#     with_items:
#       - "{{ jsondata | json_query(tenants) }}"



   - name: Create ap
     aci_ap:
       name: "{{ item.name }}"
       description: "{{ item.description }}"
       tenant: "{{ jsondata | json_query(tenants.name) }}"
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       validate_certs: false
     with_items:
       - "{{ jsondata | json_query('tenants.application_profiles') }}"



#     loop: "{{ jsondata | () }}"
#     loop_control:
#       loop_var: tn


#   - name: Create a tenant
#     aci_tenant:
#       tenant: "{{ tenants | json_query('tenants.name') }}"
#       #description: "{{ tenants | json_query(tenants.description) }}"
#       host: "{{ inventory_hostname }}"
#       username: "{{ user }}"
#       password: "{{ pass }}"
#       validate_certs: false



#   - name: create Application Profile
#     aci_ap:
#       tenant: "{{ jsondata | json_query(tenants.name) }}"
#       name: "{{ jsondata | json_query('tenants.application_profiles.name') }}"
#       description: "{{ jsondata | json_query('tenants.application_profiles.description') }}"
#       host: "{{ inventory_hostname }}"
#       username: "{{ user }}"
#       password: "{{ pass }}"
#       validate_certs: false


#     loop: "{{ tenants | json_query(tenants.application_profiles) }}"
#     loop_control:
#       loop_var: ap




#     loop: 
# "{{ tenants | json_query('tenants.name') }}"

#     with_items: "{{ application_profiles.tn }}"    
#     loop: "{{ tn.application_profiles }}"
#     loop_control:
#       loop_var: ap
       
# "{{ tenants | application_profiles.json_query(domain.server[?cluster=='cluster1'].port) }}"
