---
-  hosts: apic
   any_errors_fatal: true
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
    
   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: 'sandboxapicdc.cisco.com'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: '!v3G@!4@Y'
       private: yes
       unsafe: yes


#   - name: Calling Variabl File
#     include_vars: coding_challenge_ansible.yml

   tasks:
   - name: Display the JSON file content
       shell: cat output.txt
       register: result

   - name: save the Json data to a Variable as a Fact
       set_fact:
       jsondata: "{{ result.stdout | from_json }}"



   - name: Create a tenant
     aci_tenant:
       tenant: "{{ tn.name }}"
       description: "{{ tn.description }}"
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       validate_certs: false

     loop: "{{ tenants }}"
     loop_control:
       loop_var: tn



   - name: create Application Profile
     aci_ap:
       tenant: "{{ jsondata | json_query(tenants.name) }}"
       name: "{{ ap.name }}"
       #tenant: "{{ tenants | json_query('.name') }}" 
       description: "{{ ap.description') }}"
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       validate_certs: false


     loop: "{{ from_json | json_query("[*].tenants.application_profiles") }}"
     loop_control:
       loop_var: ap




#     loop: 
# "{{ tenants | json_query('tenants.name') }}"

#     with_items: "{{ application_profiles.tn }}"    
#     loop: "{{ tn.application_profiles }}"
#     loop_control:
#       loop_var: ap
       
# "{{ tenants | application_profiles.json_query(domain.server[?cluster=='cluster1'].port) }}"
