---
-  hosts: apic
   any_errors_fatal: true
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
    
   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: 'sandboxapicdc.cisco.com'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: '!v3G@!4@Y'
       private: yes
       unsafe: yes


   tasks:
   - name: Calling Variabl File
     include_vars: coding_challenge_ansible.yml

   - name: Create a tenant
     aci_tenant:
       tenant: "{{ tn.name }}"
       description: "{{ tn.description }}"
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       validate_certs: false
     
     loop: "{{ tenants }}"
     loop_control:
       loop_var: tn


   - name: create Application Profile
     aci_ap:
       name: "{{ tenants | json_query(application_profiles.name }}"
       tenant: "{{ tenants | json_query(tenants.name }}"
       description: "{{ tenants | json_query(application_profiles.description }}"
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       validate_certs: false
#     loop: 

#     with_items: "{{ application_profiles.tn }}"    
#     loop: "{{ tn.application_profiles }}"
#     loop_control:
#       loop_var: ap
       
