---
-  hosts: apic
   any_errors_fatal: true
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
    
   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: '10.10.20.14'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: 'C1sco12345'
       private: yes
       unsafe: yes


   tasks:
   - name: Calling Variabl File
     include_vars: coding_challenge_ansible.yml

   - name: Create a tenant
     aci_tenant:
       tenant: "{{ tn.name }}"
       description: "{{ tn.description }}"
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       validate_certs: false
       
     loop: "{{ tenants }}"
     loop_control:
       loop_var: tn


   - name: create Application Profile
     aci_ap:
       ap: "{{ ap.name }}"
       tenant: "{{ tn.name }}"
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       validate_certs: false

     loop: "{{ application_profiles }}"
     loop_control:
       loop_var: ap
