---
-  hosts: apic
   any_errors_fatal: true
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
    
   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: 'sandboxapicdc.cisco.com'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: '!v3G@!4@Y'
       private: yes
       unsafe: yes


   tasks:
   - name: Display the JSON file content
     shell: cat /root/ACI_Objects_Creator/files/source.json
     register: result

   - name: save the Json data to a Variable as a Fact
     set_fact:
       jsondata: "{{ result.stdout | from_json }}"

   - name: Print to see how it looks like
     debug:
       var: jsondata 



   - name: Display all cluster names
     debug:
       var: item
     loop: "{{ jsondata  | json_query('tenants.vrfs[*].name', wantlist=True) }}"
     
     
     # name: Display all cluster names
#     debug:
#       var: item
#     loop: "{{ jsondata  | json_query('tenants.vrfs[*].name') }}"
