---
-  hosts: apic
   any_errors_fatal: true
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
     l3out_name: 'L3_Out_Device'
     epg_4: 'External_EPG'
     L3_domain: 'ISR3945'

     
   vars:
     cred: &credentials
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       validate_certs: false
     
     

   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: '10.10.20.14'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: 'C1sco12345'
       private: yes
       unsafe: yes

   vars_files:
     - coding_challenge_ansible.yml

   tasks:
   
   - name: Create a tenant
     tags: always
     aci_tenant:
       tenant: "{{ item.name }}"
       description: "{{ item.description }}"
       <<: *credentials
     with_items:
       - "{{ tenants }}"
